### ISSUE TITLE
Pinch zoom is not working in android mobile chrome browser

### ISSUE THREAD

**Issue by dineshvabof** [gerhardsletten/react-pinch-zoom-pan#1]
![capture](https://cloud.githubusercontent.com/assets/17158940/15606103/9f3cc04e-2427-11e6-891d-96d886bdada2.JPG)

**Comment by gerhardsletten** [comment]
Hi, I don't have any Android devices, but could you check these things:

- Is the [isTouch() utility function](https://github.com/gerhardsletten/react-pinch-zoom-pan/blob/master/src/ReactPinchZoomPan.js#L9) working? 
- When the component is mounted it tries to find its size [in the resize() function](https://github.com/gerhardsletten/react-pinch-zoom-pan/blob/master/src/ReactPinchZoomPan.js#L49), could you check if `domNode.offsetWidth` and `domNode.offsetHeight` it returning something. In [mozillas docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight) the browser support not well documented 

Looks like you allready have the demo up running, so you can just run `npm start` add some console.log's and check

**Comment by dineshvabof** [comment]
https://github.com/gerhardsletten/react-pinch-zoom-pan/blob/master/src/ReactPinchZoomPan.js#L102 

**_mm.scale_** value is not working. 

It works only on Iphone. On other devices I could not make this component working. So I tried to write my own component by referring your code. Still in development mode. Attached the file.
[PinchZoom.txt](https://github.com/gerhardsletten/react-pinch-zoom-pan/files/298883/PinchZoom.txt)

**Comment by gerhardsletten** [comment]
Hi, sorry for late reply. Have been researching a little bit, and yes looks like event.scale is part of [Gesture event](https://developer.apple.com/library/ios/documentation/UserExperience/Reference/GestureEventClassReference/index.html#//apple_ref/doc/uid/TP40009353-CH6) but documentation other that on Apple site is poor. So probably you will need to check for multiple touches, and use those to find the scale yourself. Should only be to caculate the difference between inital distance between touches and current distance.

You could submit your suggestion as a pull request.

**Comment by wayofthefuture** [comment]
Were you able to get it working @dineshvabof ? Do you think updating any of the underlying libraries could help solve the problem? I was going to start looking into this and try to get a pull request going. I'm not sure where to start looking though... maybe you guys could point me in the right direction. Thanks.

**Comment by gerhardsletten** [comment]
@wayofthefuture I think its the [scale property](https://github.com/gerhardsletten/react-pinch-zoom-pan/blob/master/src/ReactPinchZoomPan.js#L118) that is not working on android. You could try to write that out as it is done for non touch devices

**Comment by pinoniq** [comment]
@gerhardsletten @wayofthefuture I like the idea of maybe changing the underlying library. Something like http://hammerjs.github.io/ could probably take away some of our pains :)

**Comment by gerhardsletten** [comment]
I did see that there is a react-hammerjs library, and it has a pinch event, so it could be used. But consideration should also be put in in size I guess. When I first wrote this library, I was looking into RSJS, but I think this was not was strictly needed, so it could maybe be left out.

**Comment by wayofthefuture** [comment]
I think rxjs was a huge dependency? would it be advantageous to use hammerjs? I think rx was about 500k or something.

**Comment by wayofthefuture** [comment]
Ok so I haven't had any time lately... if any of you want to make some cash I'm willing to compensate you to get this issue fixed.

**Comment by gerhardsletten** [comment]
@wayofthefuture Think it should work on android now, just justing the same fallback as on desktop with the missing scale property of touchmove event

**Comment by gerhardsletten** [comment]
@wayofthefuture Also stripped about 200K of bundle by using named imports and switching to `rxjs`

**Comment by wayofthefuture** [comment]
Will test when I get home. For now I am getting an error though:
> Uncaught TypeError: this.pinchSubscription.dispose is not a function

  }, {
    key: 'componentWillUnmount',
    value: function componentWillUnmount() {
      if (this.pinchSubscription) {
        this.pinchSubscription.dispose();
      }
      global.removeEventListener('resize', this.resizeThrottled);
    }
  }, {

**Comment by gerhardsletten** [comment]
Whops, probably we need to do a spesific import from rxjs like we do for other utility-functions we use here: https://github.com/gerhardsletten/react-pinch-zoom-pan/blob/master/src/ReactPinchZoomPan.js#L5

To keep depencency-size small I have tried to avoid including the whole library..

Will fix it later this evening

**Comment by gerhardsletten** [comment]
@wayofthefuture Should be fixed now

**Comment by wayofthefuture** [comment]
Very nice! It is working now and thank you for your time. Please let me know what compensation I should send you. Thanks.

**Comment by gerhardsletten** [comment]
@wayofthefuture Good to hear. No, no compensation is necessary, only happy to help!
