### ISSUE TITLE
License missing?

### ISSUE THREAD

**Issue by timschlechter** [gerhardsletten/react-pinch-zoom-pan#11]
Could you please add a license file to this repository?

**Comment by pinoniq** [comment]
The license for this project can be found in the package.json: https://github.com/gerhardsletten/react-pinch-zoom-pan/blob/master/package.json#L31

If you prefer a dedicated License file, feel free to open a pull request.

**Comment by timschlechter** [comment]
Ah, I overlooked that one. Thanks!
