### ISSUE TITLE
Unable to trigger zoom from other events

### ISSUE THREAD

**Issue by Cyberlane** [gerhardsletten/react-pinch-zoom-pan#16]
I would like to trigger "zoom" when the image is double clicked, which is a relatively common scenario for zoom, and unfortunately not possible with the current code configuration from what I can see.

Currently, you read `initialScale` on the constructor and set the `state`. However, you do not make use of `componentDidReceiveProps`... if you simply added the following, snippet of code, I could add the double click to the image myself, and simply pass in a new `scale` prop (or `initialScale` if you prefer), and I would be able to have my double click scenario, and others could do their own variants as well.

```
componentDidReceiveProps(newProps) {
  if (newProps.scale !== this.state.scale) {
    this.setState({ scale: newProps.scale });
  }
}
```

**Comment by gerhardsletten** [comment]
Thanks @Cyberlane could you supply a pull-request for it?

**Comment by Cyberlane** [comment]
@gerhardsletten I sent a PR 2 weeks ago. Any feedback?

**Comment by gerhardsletten** [comment]
Sorry, will take a look later today
