### ISSUE TITLE
Version installed via NPM doesn't match this repo..

### ISSUE THREAD

**Issue by RavenHursT** [gerhardsletten/react-pinch-zoom-pan#2]
This says the latest version of this library is `1.1.0` and was updated 5 days ago.

But this says that the latest release is `1.0.7`, back in March... https://github.com/gerhardsletten/react-pinch-zoom-pan/releases

Furthermore, the `package.json` in the source here on GH _also_ says `1.0.7`..
https://github.com/gerhardsletten/react-pinch-zoom-pan/blob/master/package.json#L3

I came across this because I was getting an "invariant violation" telling me that I was running 2 versions of React in my project (I'm still running `0.14.x`).

In the latest commit history on this project, the React dependency was updated to use `15.x` which is causing webpack to include both `0.14.x` and `15.x` in the project: https://github.com/gerhardsletten/react-pinch-zoom-pan/commit/91b3cc0ed61b2632e44d3d07ad3910c82dc98977#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R73

Looking like someone did an NPM publish from their local w/o pushing to the GH repo...

**Comment by gerhardsletten** [comment]
Hi, think I might forgot to to a git push after publishing on npm..
