### ISSUE TITLE
Vertical touch scrolling for multiple images

### ISSUE THREAD

**Issue by wayofthefuture** [gerhardsletten/react-pinch-zoom-pan#5]
We have multiple images in a vertical column on 1 page. The pinch zoom and pan works fine, but if the user tries to scroll the page down, it won't let them. They have to touch somewhere other than the image to scroll the page. Do you have any ideas as to what could allow this behavior? If you point me in the right direction, I can try to create a pull request for it. Thanks.

**Comment by wayofthefuture** [comment]
#6

**Comment by gerhardsletten** [comment]
Sorry for late merge, but now its updated!
